language: python

python:
  - "3.6"
  - "3.5"
  - "3.7-dev"

matrix:
  allow_failures:
  - python: 3.7-dev

install:
  - pip install pipenv codecov
  - pipenv install

script:
  - pipenv run coverage run --rcfile=.coveragerc myproject/manage.py test boards
  - pipenv run coverage report

after_success:
  - codecov